[phases.setup]
nixPkgs = ['python39', 'gcc', 'postgresql', 'nodejs_20']

[phases.install]
cmds = [
  'python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt',
  'cd frontend && npm install'
]

[phases.build]
cmds = [
  'cd frontend && npm run build',
  'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && daphne chat_project.asgi:application --port $PORT --bind 0.0.0.0' 